import { Link } from 'react-router';

import { LegalPageLayout } from './LegalPageLayout.tsx';
import { LEGAL_PATHS } from './legalRoutes.ts';

/**
 * Public Privacy Policy at /privacy (issue #100). Transcribed verbatim from
 * plans/legal/privacy-policy.md. §2 and §6 are rendered as real <table>
 * markup; §4 preserves the four Twilio carrier-mandated disclosures word for
 * word (non-sharing, message-frequency, message-and-data-rates, STOP/HELP).
 */
export function PrivacyPolicyPage() {
  return (
    <LegalPageLayout title="Siapp Privacy Policy" effective="22 August 2026" updated="22 August 2026">
      <p>
        Siapp (&ldquo;<strong>Siapp</strong>&rdquo;, &ldquo;<strong>we</strong>&rdquo;,
        &ldquo;<strong>us</strong>&rdquo;, &ldquo;<strong>our</strong>&rdquo;) provides a
        project-tracking and client-notification platform for construction and legal firms in
        Malaysia (the &ldquo;<strong>Service</strong>&rdquo;). This Privacy Policy explains what
        personal data we collect, how we use it, and the rights available to you under the Malaysian{' '}
        <strong>Personal Data Protection Act 2010 (&ldquo;PDPA&rdquo;)</strong>.
      </p>

      <h2>1. Who is responsible for your data</h2>
      <ul>
        <li>
          <strong>Firms (our customers)</strong> who use Siapp to manage projects are the{' '}
          <strong>data controllers</strong> of their own clients&rsquo; and collaborators&rsquo;
          personal data. Siapp acts as a <strong>data processor</strong> on their behalf.
        </li>
        <li>
          <strong>Siapp</strong> is the <strong>data controller</strong> for account, billing, and
          platform-usage data of the firms and firm users who register with us directly.
        </li>
      </ul>
      <p>
        If you are a client or collaborator of a firm and want to access, correct, or delete your
        personal data, please contact <strong>that firm</strong> — they control your data. We will
        assist the firm as their processor.
      </p>

      <h2>2. Data we collect</h2>
      <div className="legal-table-wrap">
        <table>
          <caption>Categories of personal data collected, with examples and sources.</caption>
          <thead>
            <tr>
              <th scope="col">Category</th>
              <th scope="col">Examples</th>
              <th scope="col">Source</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Account data</td>
              <td>Name, work email, password hash, role, workspace</td>
              <td>Firm user at sign-up</td>
            </tr>
            <tr>
              <td>Firm/billing data</td>
              <td>Firm name, business address, plan tier, invoices</td>
              <td>Firm; billing provider</td>
            </tr>
            <tr>
              <td>Recipient contact data</td>
              <td>
                Client/collaborator name, <strong>mobile number</strong>, email, language preference
              </td>
              <td>Entered by the firm</td>
            </tr>
            <tr>
              <td>Messaging data</td>
              <td>
                Message content, delivery/read receipts, opt-in and opt-out records, timestamps
              </td>
              <td>Generated by the Service; Twilio; Meta (WhatsApp)</td>
            </tr>
            <tr>
              <td>Project content</td>
              <td>Projects, tasks, notes, uploaded documents</td>
              <td>Firm users; clients (portal uploads)</td>
            </tr>
            <tr>
              <td>Usage &amp; device data</td>
              <td>IP address, browser type, log and diagnostic data</td>
              <td>Automatically collected</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2>3. How we use your data (lawful basis)</h2>
      <ul>
        <li>
          <strong>Provide the Service</strong> — deliver project updates, portal access, and
          notifications (performance of contract).
        </li>
        <li>
          <strong>Send notifications</strong> — outbound WhatsApp and SMS project updates on behalf
          of the firm, based on <strong>opt-in consent</strong> captured by the firm (see Section 5).
        </li>
        <li>
          <strong>Billing and account management</strong> — invoicing and support (contract /
          legitimate interest).
        </li>
        <li>
          <strong>Security, fraud prevention, and service improvement</strong> (legitimate interest).
        </li>
        <li>
          <strong>Legal compliance</strong> — retention, breach notification, lawful requests.
        </li>
      </ul>

      <h2>4. Mobile information and message-program privacy (Twilio / SMS)</h2>
      <ul>
        <li>
          <strong>No sharing or selling of mobile numbers.</strong>{' '}
          <strong>
            We do not share, sell, rent, or otherwise disclose mobile phone numbers, or the consent
            to receive messages, to any third party or affiliate for their own marketing or
            promotional purposes.
          </strong>{' '}
          Mobile numbers are used solely to deliver the messages you have opted in to receive, and
          are shared only with the sub-processors strictly necessary to deliver those messages (e.g.
          our telecommunications provider, Twilio; and, for WhatsApp, Meta). No mobile information is
          shared with third parties or affiliates for marketing or promotional purposes.
        </li>
        <li>
          <strong>Message frequency.</strong> Messages are transactional and event-driven. You will
          receive messages when project events occur (for example: project welcome, task assignment,
          status change, due-date reminders). <strong>Message frequency varies</strong> by the
          activity on your project and typically ranges from a few messages per week to occasional
          messages, depending on how active your project is.
        </li>
        <li>
          <strong>Message and data rates.</strong>{' '}
          <strong>Message and data rates may apply</strong>, depending on your mobile carrier and
          plan.
        </li>
        <li>
          <strong>Opt-out.</strong> You can opt out at any time by replying <strong>STOP</strong> to
          any message. You may reply <strong>HELP</strong> for assistance, or contact
          support@siapp.app. See our <Link to={LEGAL_PATHS.smsTerms}>SMS / Messaging Terms</Link> and{' '}
          <Link to={LEGAL_PATHS.campaignPrivacy}>Campaign Privacy Policy</Link> for full program
          terms.
        </li>
      </ul>

      <h2>5. Consent, opt-in, and opt-out</h2>
      <ul>
        <li>
          The firm captures your <strong>opt-in consent</strong> to receive WhatsApp/SMS
          notifications and records the timestamp, source, language, and consent copy.
        </li>
        <li>
          <strong>All outbound messaging is opt-in.</strong> Recipients who have not consented are
          suppressed and receive no messages.
        </li>
        <li>
          You can withdraw consent at any time by replying <strong>STOP</strong>. We process opt-outs
          across all senders and honor them going forward.
        </li>
      </ul>

      <h2>6. Who we share data with (sub-processors)</h2>
      <p>
        We share personal data only with vetted sub-processors under a Data Processing Addendum,
        strictly to operate the Service:
      </p>
      <div className="legal-table-wrap">
        <table>
          <caption>Sub-processors, their purpose, and the data shared.</caption>
          <thead>
            <tr>
              <th scope="col">Sub-processor</th>
              <th scope="col">Purpose</th>
              <th scope="col">Data</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Twilio</td>
              <td>SMS / WhatsApp message delivery</td>
              <td>Mobile number, message content, delivery status</td>
            </tr>
            <tr>
              <td>Meta (WhatsApp Business Platform)</td>
              <td>WhatsApp message delivery</td>
              <td>Mobile number, message content</td>
            </tr>
            <tr>
              <td>Google Cloud / Firebase</td>
              <td>Application hosting and storage</td>
              <td>All Service data</td>
            </tr>
            <tr>
              <td>Payment provider</td>
              <td>Billing</td>
              <td>Firm billing data</td>
            </tr>
            <tr>
              <td>Error and analytics provider</td>
              <td>Reliability and diagnostics</td>
              <td>Usage/device data</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>
        We <strong>do not</strong> sell personal data. We do not use mobile numbers for third-party
        marketing.
      </p>

      <h2>7. Cross-border transfer</h2>
      <p>
        The Service is hosted in Singapore (ap-southeast-1). Where personal data is transferred
        outside Malaysia, we ensure a comparable level of protection through contractual safeguards
        with the recipient, consistent with the PDPA.
      </p>

      <h2>8. Retention</h2>
      <p>
        We retain personal data for as long as the firm&rsquo;s account is active and as required to
        provide the Service, then delete or anonymize it in line with the firm&rsquo;s instructions
        and our legal obligations. Opt-out records are retained as needed to honor your choice.
      </p>

      <h2>9. Your rights under the PDPA</h2>
      <p>
        Subject to the PDPA, you may request to <strong>access</strong>, <strong>correct</strong>,{' '}
        <strong>withdraw consent</strong>, or request <strong>deletion</strong> of your personal
        data. If you are a client/collaborator, direct these requests to the <strong>firm</strong>{' '}
        (the data controller). For data we control directly, contact us at support@siapp.app. We aim
        to respond within 21 days.
      </p>

      <h2>10. Security</h2>
      <p>
        We apply role-based access control, encryption in transit, and access logging. In the event
        of a personal data breach, we follow our breach-response runbook and notify as required by
        law.
      </p>

      <h2>11. Children</h2>
      <p>
        The Service is intended for business users and is not directed at children under 18.
      </p>

      <h2>12. Changes to this policy</h2>
      <p>
        We may update this policy. Material changes will be notified via the Service or email, and
        the &ldquo;Last updated&rdquo; date will change.
      </p>

      <h2>13. Contact / Data Protection Officer</h2>
      <p>
        <strong>Siapp — Data Protection Officer</strong>
        <br />
        Email: support@siapp.app
        <br />
        Phone: +1 (206) 596-7128
        <br />
        Address: Kuala Lumpur, Malaysia
      </p>
    </LegalPageLayout>
  );
}
