import type { ISeedDefinition } from '../seedTypes.js';

/**
 * Building-plan-approval starter project seed (44 tasks, 7 phases).
 * D-031: seeded once per tenant during provisioning; no D-032 fields.
 *
 * Mirrors the Malaysian building-approval workflow: appointment &
 * preliminary design → KM (Kebenaran Merancang) submission → Building Plan
 * (BP) submission → infrastructure approvals & start-work permit →
 * construction → CCC → final handover, including OSC online submission
 * rounds, Bomba and jabatan-luar approvals, and staged CCC certification.
 *
 * milestone tasks (first + last in each phase) are client-visible and
 * WhatsApp-notified; internal work items are firm-only.
 *
 * dependsOn links wire a sequential dependency graph across phases
 * (last task of phase N → first task of phase N+1).
 */
export const buildingApprovalSeed: ISeedDefinition = {
  vertical: 'construction',
  label: 'Building Plan Approval',
  phases: [
    { id: 'phase-appointment', name: 'Appointment & Preliminary Design', order: 1 },
    { id: 'phase-km-submission', name: 'KM Submission (Kebenaran Merancang)', order: 2 },
    { id: 'phase-bp-submission', name: 'Building Plan (BP) Submission', order: 3 },
    { id: 'phase-infra-permit', name: 'Infrastructure & Start-Work Permit', order: 4 },
    { id: 'phase-construction', name: 'Construction Stage', order: 5 },
    { id: 'phase-ccc', name: 'CCC (Certificate of Completion & Compliance)', order: 6 },
    { id: 'phase-handover', name: 'Final Handover', order: 7 },
  ],
  tasks: [
    // ── Phase 1: Appointment & Preliminary Design ──────────────────────────
    {
      id: 't-ap-01',
      title: 'Client appoints architect',
      order: 1,
      phaseRef: 'phase-appointment',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-ap-02',
      title: 'Concept plan and preliminary design',
      order: 2,
      phaseRef: 'phase-appointment',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ap-03',
      title: 'Zoning check and land search (KTK)',
      order: 3,
      phaseRef: 'phase-appointment',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ap-04',
      title: 'Appoint consultants (C&S, M&E, town planner, QS)',
      order: 4,
      phaseRef: 'phase-appointment',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ap-05',
      title: 'Client sign-off on preliminary design',
      order: 5,
      phaseRef: 'phase-appointment',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 2: KM Submission (Kebenaran Merancang) ───────────────────────
    {
      id: 't-km-01',
      title: 'Compile KM submission documentation',
      order: 6,
      phaseRef: 'phase-km-submission',
      dependsOn: ['t-ap-05'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-km-02',
      title: 'Land survey plan (pelan ukur)',
      order: 7,
      phaseRef: 'phase-km-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-km-03',
      title: 'Prepare KM layout plan (pelan KM)',
      order: 8,
      phaseRef: 'phase-km-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-km-04',
      title: 'Submit KM via OSC online',
      order: 9,
      phaseRef: 'phase-km-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-km-05',
      title: 'Respond to OSC department comments (komen jabatan)',
      order: 10,
      phaseRef: 'phase-km-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-km-06',
      title: 'KM approved (Kebenaran Merancang)',
      order: 11,
      phaseRef: 'phase-km-submission',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 3: Building Plan (BP) Submission ─────────────────────────────
    {
      id: 't-bp-01',
      title: 'Prepare 2D building plan (pelan BP) drawings',
      order: 12,
      phaseRef: 'phase-bp-submission',
      dependsOn: ['t-km-06'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-02',
      title: 'Pre-consultation with local authority (pre-consult)',
      order: 13,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-03',
      title: 'Client signature on BP submission set',
      order: 14,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-04',
      title: 'Submit plans to Bomba',
      order: 15,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-05',
      title: 'Bomba approval (kelulusan Bomba)',
      order: 16,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-06',
      title: 'External agency submissions (jabatan luar)',
      order: 17,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-07',
      title: 'Submit BP via OSC online',
      order: 18,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-08',
      title: 'Respond to OSC comments and submit hardcopy',
      order: 19,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-09',
      title: 'Attend OSC meeting',
      order: 20,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-10',
      title: 'Compliance confirmation (Akuan Pematuhan)',
      order: 21,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-11',
      title: 'Final vetting (semakan akhir) and endorsement',
      order: 22,
      phaseRef: 'phase-bp-submission',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-bp-12',
      title: 'BP approved — approved plan (pelan lulus) issued',
      order: 23,
      phaseRef: 'phase-bp-submission',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 4: Infrastructure & Start-Work Permit ────────────────────────
    {
      id: 't-in-01',
      title: 'Prepare infrastructure plan submissions',
      order: 24,
      phaseRef: 'phase-infra-permit',
      dependsOn: ['t-bp-12'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-02',
      title: 'Earthworks plan approval (kerja tanah)',
      order: 25,
      phaseRef: 'phase-infra-permit',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-03',
      title: 'Street lighting approval (lampu jalan)',
      order: 26,
      phaseRef: 'phase-infra-permit',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-04',
      title: 'Road and drainage approval (jalan & longkang)',
      order: 27,
      phaseRef: 'phase-infra-permit',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-05',
      title: 'Landscape plan approval (landskap)',
      order: 28,
      phaseRef: 'phase-infra-permit',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-06',
      title: 'RC / structural plan submission',
      order: 29,
      phaseRef: 'phase-infra-permit',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-in-07',
      title: 'Start-work permit issued (Permit Memulakan Kerja)',
      order: 30,
      phaseRef: 'phase-infra-permit',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 5: Construction Stage ────────────────────────────────────────
    {
      id: 't-cs-01',
      title: 'Site possession and construction start',
      order: 31,
      phaseRef: 'phase-construction',
      dependsOn: ['t-in-07'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-cs-02',
      title: 'Periodic site supervision',
      order: 32,
      phaseRef: 'phase-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cs-03',
      title: "Issue architect's instructions (AI)",
      order: 33,
      phaseRef: 'phase-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cs-04',
      title: 'Regular site meetings',
      order: 34,
      phaseRef: 'phase-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cs-05',
      title: 'Construction substantially complete',
      order: 35,
      phaseRef: 'phase-construction',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 6: CCC ───────────────────────────────────────────────────────
    {
      id: 't-cc-01',
      title: 'Compile staged certifications (Borang G1–G21)',
      order: 36,
      phaseRef: 'phase-ccc',
      dependsOn: ['t-cs-05'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-cc-02',
      title: 'Final statutory inspections (Bomba, TNB, water)',
      order: 37,
      phaseRef: 'phase-ccc',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cc-03',
      title: 'Resolve outstanding CCC conditions',
      order: 38,
      phaseRef: 'phase-ccc',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cc-04',
      title: 'Lodge CCC with LAM and local authority',
      order: 39,
      phaseRef: 'phase-ccc',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cc-05',
      title: 'CCC issued by architect',
      order: 40,
      phaseRef: 'phase-ccc',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 7: Final Handover ────────────────────────────────────────────
    {
      id: 't-ho-01',
      title: 'Final inspection with client',
      order: 41,
      phaseRef: 'phase-handover',
      dependsOn: ['t-cc-05'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-02',
      title: 'QS final accounts',
      order: 42,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-03',
      title: 'Defects rectification',
      order: 43,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-04',
      title: 'Key handover to client',
      order: 44,
      phaseRef: 'phase-handover',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
  ],
};
