import type { ISeedDefinition } from '../seedTypes.js';

/**
 * Conveyancing starter project seed (~30 tasks, 5 phases).
 * D-031: seeded once per tenant during provisioning; no D-032 fields.
 *
 * Client-visible / WhatsApp tasks mirror the key client touchpoints:
 * SPA execution, stamp duty payment, lodge transfer, and completion.
 */
export const conveyancingSeed: ISeedDefinition = {
  vertical: 'legal',
  label: 'Conveyancing',
  phases: [
    { id: 'phase-instruction', name: 'Instruction & Due Diligence', order: 1 },
    { id: 'phase-spa', name: 'Sale & Purchase Agreement', order: 2 },
    { id: 'phase-stamp', name: 'Stamp Duty & Adjudication', order: 3 },
    { id: 'phase-transfer', name: 'Transfer & Registration', order: 4 },
    { id: 'phase-completion', name: 'Completion', order: 5 },
  ],
  tasks: [
    // ── Phase 1: Instruction & Due Diligence ───────────────────────────────
    {
      id: 't-id-01',
      title: 'Receive client instruction and KYC documents',
      order: 1,
      phaseRef: 'phase-instruction',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-id-02',
      title: 'Title search at land registry',
      order: 2,
      phaseRef: 'phase-instruction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-id-03',
      title: 'Bankruptcy and winding-up search',
      order: 3,
      phaseRef: 'phase-instruction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-id-04',
      title: 'CKHT (Real Property Gains Tax) assessment',
      order: 4,
      phaseRef: 'phase-instruction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-id-05',
      title: 'Due diligence complete — proceed confirmed',
      order: 5,
      phaseRef: 'phase-instruction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },

    // ── Phase 2: Sale & Purchase Agreement ────────────────────────────────
    {
      id: 't-spa-01',
      title: 'Draft Sale & Purchase Agreement',
      order: 6,
      phaseRef: 'phase-spa',
      dependsOn: ['t-id-05'],
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-spa-02',
      title: 'SPA sent to client for review',
      order: 7,
      phaseRef: 'phase-spa',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-spa-03',
      title: 'Incorporate client comments and finalise SPA',
      order: 8,
      phaseRef: 'phase-spa',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-spa-04',
      title: 'SPA executed by all parties',
      order: 9,
      phaseRef: 'phase-spa',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-spa-05',
      title: 'Deposit received and receipted',
      order: 10,
      phaseRef: 'phase-spa',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-spa-06',
      title: 'Loan documentation (if applicable) — completed',
      order: 11,
      phaseRef: 'phase-spa',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },

    // ── Phase 3: Stamp Duty & Adjudication ────────────────────────────────
    {
      id: 't-sd-01',
      title: 'Prepare and submit Form 14A and stamp duty assessment',
      order: 12,
      phaseRef: 'phase-stamp',
      dependsOn: ['t-spa-04'],
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-sd-02',
      title: 'LHDN adjudication (if applicable)',
      order: 13,
      phaseRef: 'phase-stamp',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-sd-03',
      title: 'Client pays stamp duty',
      order: 14,
      phaseRef: 'phase-stamp',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-sd-04',
      title: 'Stamp certificate received',
      order: 15,
      phaseRef: 'phase-stamp',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-sd-05',
      title: 'SPA stamped and returned',
      order: 16,
      phaseRef: 'phase-stamp',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },

    // ── Phase 4: Transfer & Registration ──────────────────────────────────
    {
      id: 't-tr-01',
      title: 'Obtain consent from State Authority (if required)',
      order: 17,
      phaseRef: 'phase-transfer',
      dependsOn: ['t-sd-03'],
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-02',
      title: 'Prepare Memorandum of Transfer (Form 14A)',
      order: 18,
      phaseRef: 'phase-transfer',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-03',
      title: 'Execution of Form 14A by vendor',
      order: 19,
      phaseRef: 'phase-transfer',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-04',
      title: 'Lodge transfer at Land Office',
      order: 20,
      phaseRef: 'phase-transfer',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-05',
      title: 'Charge instrument (bank) lodged (if applicable)',
      order: 21,
      phaseRef: 'phase-transfer',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-06',
      title: 'Land Office presentation and registration',
      order: 22,
      phaseRef: 'phase-transfer',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-tr-07',
      title: 'New title issued in purchaser\'s name',
      order: 23,
      phaseRef: 'phase-transfer',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },

    // ── Phase 5: Completion ────────────────────────────────────────────────
    {
      id: 't-cp-01',
      title: 'Final statement of account prepared',
      order: 24,
      phaseRef: 'phase-completion',
      dependsOn: ['t-tr-04'],
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-02',
      title: 'Balance purchase price received',
      order: 25,
      phaseRef: 'phase-completion',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-03',
      title: 'Disburse purchase price to vendor',
      order: 26,
      phaseRef: 'phase-completion',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-04',
      title: 'Release keys to purchaser',
      order: 27,
      phaseRef: 'phase-completion',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-05',
      title: 'Issue completion notice to all parties',
      order: 28,
      phaseRef: 'phase-completion',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-06',
      title: 'Original title delivered to purchaser / bank',
      order: 29,
      phaseRef: 'phase-completion',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-cp-07',
      title: 'File closed and archived',
      order: 30,
      phaseRef: 'phase-completion',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
  ],
};
