import type { ISeedDefinition } from '../seedTypes.js';

/**
 * Residential-build starter project seed (~60 tasks, 7 phases).
 * D-031: seeded once per tenant during provisioning; no D-032 fields.
 *
 * milestone tasks (first + last in each phase) are client-visible and
 * WhatsApp-notified; internal work items are firm-only.
 *
 * dependsOn links wire a sequential dependency graph across phases
 * (last task of phase N → first task of phase N+1).
 */
export const residentialBuildSeed: ISeedDefinition = {
  vertical: 'construction',
  label: 'Residential Build',
  phases: [
    { id: 'phase-pre-construction', name: 'Pre-Construction', order: 1 },
    { id: 'phase-foundation', name: 'Foundation', order: 2 },
    { id: 'phase-structure', name: 'Structure', order: 3 },
    { id: 'phase-mep', name: 'MEP Rough-In', order: 4 },
    { id: 'phase-finishes', name: 'Finishes', order: 5 },
    { id: 'phase-fitout', name: 'Fit-Out', order: 6 },
    { id: 'phase-handover', name: 'Handover', order: 7 },
  ],
  tasks: [
    // ── Phase 1: Pre-Construction ──────────────────────────────────────────
    {
      id: 't-pc-01',
      title: 'Site survey and soil test',
      order: 1,
      phaseRef: 'phase-pre-construction',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-02',
      title: 'Architectural plan submission',
      order: 2,
      phaseRef: 'phase-pre-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-03',
      title: 'Structural engineering drawings',
      order: 3,
      phaseRef: 'phase-pre-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-04',
      title: 'M&E engineering drawings',
      order: 4,
      phaseRef: 'phase-pre-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-05',
      title: 'Building permit approval',
      order: 5,
      phaseRef: 'phase-pre-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-06',
      title: 'Site hoarding and security setup',
      order: 6,
      phaseRef: 'phase-pre-construction',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-pc-07',
      title: 'Pre-construction site briefing complete',
      order: 7,
      phaseRef: 'phase-pre-construction',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 2: Foundation ────────────────────────────────────────────────
    {
      id: 't-f-01',
      title: 'Foundation excavation started',
      order: 8,
      phaseRef: 'phase-foundation',
      dependsOn: ['t-pc-07'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-02',
      title: 'Piling works',
      order: 9,
      phaseRef: 'phase-foundation',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-03',
      title: 'Blinding concrete',
      order: 10,
      phaseRef: 'phase-foundation',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-04',
      title: 'Foundation rebar installation',
      order: 11,
      phaseRef: 'phase-foundation',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-05',
      title: 'Foundation formwork and shuttering',
      order: 12,
      phaseRef: 'phase-foundation',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-06',
      title: 'Ground beam concrete pour',
      order: 13,
      phaseRef: 'phase-foundation',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-f-07',
      title: 'Foundation and ground beam inspection passed',
      order: 14,
      phaseRef: 'phase-foundation',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 3: Structure ─────────────────────────────────────────────────
    {
      id: 't-s-01',
      title: 'Ground-floor slab casting',
      order: 15,
      phaseRef: 'phase-structure',
      dependsOn: ['t-f-07'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-02',
      title: 'Brick wall — ground floor',
      order: 16,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-03',
      title: 'Columns and beams — ground floor',
      order: 17,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-04',
      title: 'First-floor slab casting',
      order: 18,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-05',
      title: 'Brick wall — first floor',
      order: 19,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-06',
      title: 'Columns and beams — first floor',
      order: 20,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-07',
      title: 'Roof truss installation',
      order: 21,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-08',
      title: 'Roof tiling',
      order: 22,
      phaseRef: 'phase-structure',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-s-09',
      title: 'Structure complete — inspection passed',
      order: 23,
      phaseRef: 'phase-structure',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 4: MEP Rough-In ──────────────────────────────────────────────
    {
      id: 't-mep-01',
      title: 'Plumbing rough-in started',
      order: 24,
      phaseRef: 'phase-mep',
      dependsOn: ['t-s-09'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-mep-02',
      title: 'Electrical first fix (conduit and wiring)',
      order: 25,
      phaseRef: 'phase-mep',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-mep-03',
      title: 'Air-conditioning piping rough-in',
      order: 26,
      phaseRef: 'phase-mep',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-mep-04',
      title: 'Drainage and sanitary piping',
      order: 27,
      phaseRef: 'phase-mep',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-mep-05',
      title: 'MEP rough-in inspection passed',
      order: 28,
      phaseRef: 'phase-mep',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 5: Finishes ──────────────────────────────────────────────────
    {
      id: 't-fin-01',
      title: 'Wall plastering — ground floor',
      order: 29,
      phaseRef: 'phase-finishes',
      dependsOn: ['t-mep-05'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-02',
      title: 'Wall plastering — first floor',
      order: 30,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-03',
      title: 'Ceiling board installation',
      order: 31,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-04',
      title: 'Floor tile — ground floor',
      order: 32,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-05',
      title: 'Floor tile — first floor',
      order: 33,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-06',
      title: 'Wall tile — wet areas',
      order: 34,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-07',
      title: 'Paint — primer coat',
      order: 35,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-08',
      title: 'Paint — first finish coat',
      order: 36,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-09',
      title: 'Paint — final coat',
      order: 37,
      phaseRef: 'phase-finishes',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fin-10',
      title: 'Finishes inspection complete',
      order: 38,
      phaseRef: 'phase-finishes',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 6: Fit-Out ───────────────────────────────────────────────────
    {
      id: 't-fo-01',
      title: 'Electrical second fix (switches, sockets, DB)',
      order: 39,
      phaseRef: 'phase-fitout',
      dependsOn: ['t-fin-10'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-02',
      title: 'Sanitary fitting installation',
      order: 40,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-03',
      title: 'Air-conditioning unit installation',
      order: 41,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-04',
      title: 'Kitchen cabinet installation',
      order: 42,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-05',
      title: 'Wardrobe and built-in joinery',
      order: 43,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-06',
      title: 'Door and window frames — final',
      order: 44,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-07',
      title: 'Staircase railings and balustrade',
      order: 45,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-08',
      title: 'Grilles and security screen installation',
      order: 46,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-09',
      title: 'Landscape and external works',
      order: 47,
      phaseRef: 'phase-fitout',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-fo-10',
      title: 'Fit-out complete',
      order: 48,
      phaseRef: 'phase-fitout',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },

    // ── Phase 7: Handover ──────────────────────────────────────────────────
    {
      id: 't-ho-01',
      title: 'Pre-handover defect check',
      order: 49,
      phaseRef: 'phase-handover',
      dependsOn: ['t-fo-10'],
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-02',
      title: 'Defect rectification',
      order: 50,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-03',
      title: 'TNB power connection application',
      order: 51,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-04',
      title: 'Water meter connection application',
      order: 52,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-05',
      title: 'Certificate of Completion (CCC) application',
      order: 53,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-06',
      title: 'Certificate of Completion (CCC) received',
      order: 54,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-07',
      title: 'Final walkthrough with client',
      order: 55,
      phaseRef: 'phase-handover',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-08',
      title: 'Keys and documents handover',
      order: 56,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-09',
      title: 'As-built drawings submission',
      order: 57,
      phaseRef: 'phase-handover',
      visibleToClient: false,
      sendWhatsapp: false,
      restrictedToDepartments: [],
    },
    {
      id: 't-ho-10',
      title: 'Project complete — handover signed off',
      order: 58,
      phaseRef: 'phase-handover',
      visibleToClient: true,
      sendWhatsapp: true,
      restrictedToDepartments: [],
    },
  ],
};
